export default defineAppConfig({
  profile: {
    name: 'Favour Emeka',
    available: true,
    avatar: '/images/avatar.jpg',
    resume: 'https://drive.google.com/file/d/15NGRKx8cc52hd0vQWwEIHPwD-hyGqHqe/view?usp=sharing',
    stack: [
      { name: 'Vue', icon: 'i-logos-vue', url: 'https://vuejs.org/' },
      { name: 'Nuxt', icon: 'i-logos-nuxt-icon', url: 'https://nuxt.com/' },
      { name: 'JavaScript', icon: 'i-logos-javascript', url: 'https://en.wikipedia.org/wiki/JavaScript' },
      { name: 'TypeScript', icon: 'i-logos-typescript-icon', url: 'https://www.typescriptlang.org/' },
      { name: 'Unocss', icon: 'i-logos-unocss', url: 'https://unocss.dev/' },
      { name: 'Scss', icon: 'i-logos-sass', url: 'https://sass-lang.com/' },
      { name: 'Pinia', icon: 'i-logos-pinia', url: 'https://pinia.vuejs.org/' },
      { name: 'Firebase', icon: 'i-logos-firebase', url: 'https://firebase.google.com/' },
      { name: 'Git', icon: 'i-logos-git-icon', url: 'https://git-scm.com/' },
      { name: 'Vercel', icon: 'i-logos-vercel-icon', url: 'https://vercel.com/' },
      { name: 'Figma', icon: 'i-logos-figma', url: 'https://www.figma.com/' },
      { name: 'VsCode', icon: 'i-logos-visual-studio-code', url: 'https://code.visualstudio.com/' },
      { name: 'Npm', icon: 'i-logos-npm-icon', url: 'https://www.npmjs.com/' },
    ],
    contact: [
      { name: 'Phone', icon: 'i-hugeicons-call', value: '+234-802-438-3756', url: 'tel:+234-802-438-3756' },
      { name: 'Email', icon: 'i-hugeicons-mail-01', url: 'mailto:favorodera@gmail', value: 'favorodera@gmail.com' },
      { name: 'Github', icon: 'i-hugeicons-github', url: 'https://github.com/favorodera', value: 'favorodera' },
      { name: 'X (Twitter)', icon: 'i-hugeicons-new-twitter', url: 'https://x.com/favorodera', value: '@favorodera' },
      { name: 'Linkedin', icon: 'i-hugeicons-linkedin-02', url: 'https://linkedin.com/in/favorodera', value: 'favorodera' },
    ],
  },
})
